### ISSUE TITLE
API server

### ISSUE THREAD

**Issue by AndroidNextdoor** [AndroidNextdoor/myFirstAngularApi#1]
I'm having difficulty in following some of the tutorials that are out the discussing creating the MEAN app.

When I run the api, I'm not getting my server to run on port 3000. Even though I've followed this tutorial: https://scotch.io/tutorials/mean-app-with-angular-2-and-the-angular-cli , I'm not having any luck.

Here are a bunch of the other tutorials that I've read to get this working:
https://scotch.io/tutorials/build-a-restful-api-using-node-and-express-4
https://scotch.io/tutorials/setting-up-a-mean-stack-single-page-application
https://malcoded.com/posts/angular-backend-express

Any ideas?

**Comment by mycompassspins** [comment]
So, I assume you intend to run the node server after you've built the Angular app (`ng build`)? If that's the case, your node server won't work until there's a `dist` directory (until you've built the Angular app, in other words). So building is step one. Once built you'll see your mistake when looking in the `dist` directory and matching that against where you're telling Express to look for static files.

Also, you don't need to required the `http` module. You can do `app.listen` rather than `server.listen`.

**Comment by AndroidNextdoor** [comment]
I feel like I'm getting a better grasp of this finally. Thank you for the very helpful pointers. 

I had to install a specific version of rxjs using `npm install rxjs@6 rxjs-compat@6 --save`, but i am closer to the end result. A little more and I should have this up and working.

Feel free to check out my progress if you'd like.
